# Generated by Django 4.1.5 on 2023-01-24 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('Reviewer_Id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
    ]
