# Generated by Django 4.1.5 on 2023-01-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Reviewer_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.reviewer'),
        ),
    ]
