# Generated by Django 4.1.5 on 2023-01-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_article_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Reviewer_Id',
            new_name='Reviewer',
        ),
    ]
